version: '3.7'
services:
    app:
        build:
            context: docker/php
        container_name: phpFT
        restart: unless-stopped
        tty: true
        ports:
            - "9000:9000"
        environment:
            SERVICE_NAME: php8
            SERVICE_TAGS: dev
        volumes:
            - ./:/var/www:cached
        networks:
            - app-network

    nginx:
        build:
            context: docker/nginx
        container_name: nginxFT
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
        depends_on:
            - app
        networks:
            - app-network

    db:
        container_name: mysqlFT
        image: mysql:8.0
        command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: unless-stopped
        tty: true
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: mvp
   #      MYSQL_USER: sandbox_user
   #      MYSQL_PASSWORD: passpass
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        ports:
          - '3306:3306'
        volumes:
            - db:/var/lib/mysql
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
  db:
    driver: local
